export const HOME_CONTENT_PADDING_H = 16;
export const HOME_CONTENT_PADDING_TOP = 12;
export const HOME_TAB_BAR_HEIGHT = 60;
export const HOME_TAB_BAR_MARGIN = 4;
export const HOME_BOTTOM_BAR_CLEARANCE = HOME_TAB_BAR_HEIGHT + HOME_TAB_BAR_MARGIN * 2 + 24;
export const HOME_CONTENT_PADDING_BOTTOM = HOME_BOTTOM_BAR_CLEARANCE;
export const HOME_LIST_BOTTOM_PADDING = HOME_BOTTOM_BAR_CLEARANCE + 12;
